### ISSUE TITLE
Show parameter references

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-uk#404]
Currently, parameters show only their default values. It would be helpful to have an (i) symbol, which on hover or click shows the references for a particular parameter. In OpenFisca, parameters with references have the structure:

```yaml
description:
values:
  ...
metadata:
  reference:
    - title: Reference title
      href: https://reference.gov/link
```

Adding this will require:
* Ensuring reference metadata is passed from the `/parameters` endpoint
* Showing the hover-over card and the (i) component with the relevant links
